# ============================================================
# LLM-ASSISTED ETL PIPELINE EXECUTOR
# ============================================================

import os
import time
import pandas as pd


class ETLExecutor:
    """
    Executes the ETL pipeline generated by the LLM.
    """

    # ========================================================
    # PROJECT DIRECTORIES
    # ========================================================

    BASE_DIR = os.path.dirname(
        os.path.dirname(
            os.path.abspath(__file__)
        )
    )

    RAW_DATA_DIR = os.path.join(
        BASE_DIR,
        "data",
        "raw"
    )

    PROCESSED_DATA_DIR = os.path.join(
        BASE_DIR,
        "data",
        "processed"
    )

    # ========================================================
    # CORRECT DATASET -> FILE MAPPING
    # ========================================================

    DATASET_FILES = {
        "customers": "olist_customers_dataset.csv",

        "orders": "olist_orders_dataset.csv",

        "order_items": "olist_order_items_dataset.csv",

        "payments": "olist_order_payments_dataset.csv",

        "products": "olist_products_dataset.csv"
    }

    # ========================================================
    # INITIALIZATION
    # ========================================================

    def __init__(self):

        os.makedirs(
            self.PROCESSED_DATA_DIR,
            exist_ok=True
        )

        self.dataframes = {}

        self.final_result = None

        self.output_path = None

        self.start_time = None

    # ========================================================
    # GET DATASET PATH
    # ========================================================

    def get_dataset_path(self, dataset):

        if dataset not in self.DATASET_FILES:

            raise ValueError(
                f"Unknown dataset: {dataset}"
            )

        filename = self.DATASET_FILES[dataset]

        path = os.path.join(
            self.RAW_DATA_DIR,
            filename
        )

        return path

    # ========================================================
    # LOAD DATASET
    # ========================================================

    def load_dataset(self, dataset):

        path = self.get_dataset_path(
            dataset
        )

        if not os.path.exists(path):

            raise FileNotFoundError(
                f"Dataset not found: {path}"
            )

        df = pd.read_csv(path)

        self.dataframes[dataset] = df

        print(
            f"[LOAD] {dataset} loaded successfully "
            f"({len(df)} rows)"
        )

        return df

    # ========================================================
    # CLEAN DATASET
    # ========================================================

    def clean_dataset(self, dataset):

        if dataset not in self.dataframes:

            raise ValueError(
                f"Dataset '{dataset}' has not been loaded."
            )

        df = self.dataframes[dataset]

        rows_before = len(df)

        missing_before = int(
            df.isnull().sum().sum()
        )

        duplicates_before = int(
            df.duplicated().sum()
        )

        # ----------------------------------------------------
        # Remove duplicate rows
        # ----------------------------------------------------

        df = df.drop_duplicates()

        # ----------------------------------------------------
        # Handle missing values
        #
        # Numeric columns -> median
        # Text columns    -> empty string
        # ----------------------------------------------------

        for column in df.columns:

            if df[column].isnull().any():

                if pd.api.types.is_numeric_dtype(
                    df[column]
                ):

                    median_value = df[column].median()

                    if pd.isna(median_value):
                        median_value = 0

                    df[column] = df[column].fillna(
                        median_value
                    )

                else:

                    df[column] = df[column].fillna(
                        ""
                    )

        rows_after = len(df)

        missing_after = int(
            df.isnull().sum().sum()
        )

        duplicates_after = int(
            df.duplicated().sum()
        )

        self.dataframes[dataset] = df

        print(
            f"[CLEAN] {dataset}"
        )

        print(
            f"    Rows before      : {rows_before}"
        )

        print(
            f"    Rows after       : {rows_after}"
        )

        print(
            f"    Missing before   : {missing_before}"
        )

        print(
            f"    Missing after    : {missing_after}"
        )

        print(
            f"    Duplicates before: {duplicates_before}"
        )

        print(
            f"    Duplicates after : {duplicates_after}"
        )

        return df

    # ========================================================
    # TRANSFORM DATASET
    # ========================================================

    def transform_dataset(
        self,
        dataset,
        details=""
    ):

        if dataset not in self.dataframes:

            raise ValueError(
                f"Dataset '{dataset}' has not been loaded."
            )

        df = self.dataframes[dataset]

        print(
            f"[TRANSFORM] {dataset}"
        )

        print(
            f"    Instruction: {details}"
        )

        # ----------------------------------------------------
        # ORDERS
        # ----------------------------------------------------

        if dataset == "orders":

            date_columns = [
                "order_purchase_timestamp",
                "order_approved_at",
                "order_delivered_carrier_date",
                "order_delivered_customer_date",
                "order_estimated_delivery_date"
            ]

            for column in date_columns:

                if column in df.columns:

                    df[column] = pd.to_datetime(
                        df[column],
                        errors="coerce"
                    )

        # ----------------------------------------------------
        # PAYMENTS
        # ----------------------------------------------------

        elif dataset == "payments":

            numeric_columns = [
                "payment_sequential",
                "payment_installments",
                "payment_value"
            ]

            for column in numeric_columns:

                if column in df.columns:

                    df[column] = pd.to_numeric(
                        df[column],
                        errors="coerce"
                    )

            # There is NO payment date column in the
            # Olist payments dataset.
            #
            # Therefore we only convert the actual
            # numeric payment columns.

        # ----------------------------------------------------
        # ORDER ITEMS
        # ----------------------------------------------------

        elif dataset == "order_items":

            numeric_columns = [
                "order_item_id",
                "price",
                "freight_value"
            ]

            for column in numeric_columns:

                if column in df.columns:

                    df[column] = pd.to_numeric(
                        df[column],
                        errors="coerce"
                    )

            if "shipping_limit_date" in df.columns:

                df["shipping_limit_date"] = pd.to_datetime(
                    df["shipping_limit_date"],
                    errors="coerce"
                )

        # ----------------------------------------------------
        # PRODUCTS
        # ----------------------------------------------------

        elif dataset == "products":

            numeric_columns = [
                "product_name_lenght",
                "product_description_lenght",
                "product_photos_qty",
                "product_weight_g",
                "product_length_cm",
                "product_height_cm",
                "product_width_cm"
            ]

            for column in numeric_columns:

                if column in df.columns:

                    df[column] = pd.to_numeric(
                        df[column],
                        errors="coerce"
                    )

        # ----------------------------------------------------
        # CUSTOMERS
        # ----------------------------------------------------

        elif dataset == "customers":

            # Customer IDs remain strings.
            #
            # No special transformation is required.

            pass

        self.dataframes[dataset] = df

        print(
            f"    Transformation completed "
            f"({df.shape[0]} rows, "
            f"{df.shape[1]} columns)"
        )

        return df

    # ========================================================
    # JOIN DATASETS
    # ========================================================

    def join_datasets(
        self,
        dataset,
        join_with,
        join_key
    ):

        if dataset not in self.dataframes:

            raise ValueError(
                f"Dataset '{dataset}' has not been loaded."
            )

        if join_with not in self.dataframes:

            raise ValueError(
                f"Dataset '{join_with}' has not been loaded."
            )

        left_df = self.dataframes[dataset]

        right_df = self.dataframes[join_with]

        if join_key not in left_df.columns:

            raise KeyError(
                f"Join key '{join_key}' "
                f"not found in {dataset}."
            )

        if join_key not in right_df.columns:

            raise KeyError(
                f"Join key '{join_key}' "
                f"not found in {join_with}."
            )

        # Make join columns compatible

        left_df[join_key] = (
            left_df[join_key]
            .astype(str)
        )

        right_df[join_key] = (
            right_df[join_key]
            .astype(str)
        )

        print(
            f"[JOIN] {dataset} + {join_with}"
        )

        print(
            f"    Join key     : {join_key}"
        )

        merged_df = pd.merge(
            left_df,
            right_df,
            on=join_key,
            how="inner",
            suffixes=(
                "",
                "_right"
            )
        )

        self.final_result = merged_df

        print(
            f"    Result rows  : "
            f"{merged_df.shape[0]}"
        )

        print(
            f"    Result columns: "
            f"{merged_df.shape[1]}"
        )

        return merged_df

    # ========================================================
    # GET CURRENT RESULT
    # ========================================================

    def get_current_result(self):

        if self.final_result is not None:

            return self.final_result

        if self.dataframes:

            # Return the last loaded/processed dataframe

            last_dataset = list(
                self.dataframes.keys()
            )[-1]

            return self.dataframes[
                last_dataset
            ]

        raise ValueError(
            "No data available to store."
        )

    # ========================================================
    # STORE RESULT
    # ========================================================

    def store_result(
        self,
        pipeline
    ):

        df = self.get_current_result()

        datasets = pipeline.get(
            "datasets",
            []
        )

        # ----------------------------------------------------
        # Determine a meaningful filename
        # ----------------------------------------------------

        if len(datasets) == 1:

            filename = (
                f"{datasets[0]}.csv"
            )

        elif len(datasets) == 2:

            filename = (
                f"{datasets[0]}_"
                f"{datasets[1]}.csv"
            )

        else:

            filename = "final_result.csv"

        self.output_path = os.path.join(
            self.PROCESSED_DATA_DIR,
            filename
        )

        df.to_csv(
            self.output_path,
            index=False
        )

        print(
            "\n[STORE] Result saved successfully:"
        )

        print(
            f"    {self.output_path}"
        )

        print(
            f"    Rows    : {df.shape[0]}"
        )

        print(
            f"    Columns : {df.shape[1]}"
        )

        return df

    # ========================================================
    # VALIDATION
    # ========================================================

    def validate_result(self):

        df = self.get_current_result()

        rows = df.shape[0]

        columns = df.shape[1]

        total_missing = int(
            df.isnull().sum().sum()
        )

        duplicate_rows = int(
            df.duplicated().sum()
        )

        print(
            "\n--- VALIDATION ---"
        )

        print(
            f"Final Row Count       : {rows}"
        )

        print(
            f"Final Column Count    : {columns}"
        )

        print(
            f"Total Missing Values  : "
            f"{total_missing}"
        )

        print(
            f"Duplicate Rows        : "
            f"{duplicate_rows}"
        )

        print(
            "\nMissing Values per Column:"
        )

        missing_by_column = (
            df.isnull()
            .sum()
        )

        missing_by_column = (
            missing_by_column[
                missing_by_column > 0
            ]
        )

        if missing_by_column.empty:

            print(
                "No missing values found."
            )

        else:

            print(
                missing_by_column
            )

        if (
            total_missing == 0
            and duplicate_rows == 0
        ):

            print(
                "\n# Validation completed successfully."
            )

        else:

            print(
                "\n# Validation completed "
                "with data quality issues."
            )

        return {
            "rows": rows,
            "columns": columns,
            "missing_values": total_missing,
            "duplicate_rows": duplicate_rows
        }

    # ========================================================
    # EXECUTE PIPELINE
    # ========================================================

    def execute_pipeline(
        self,
        pipeline
    ):

        self.start_time = time.perf_counter()

        pipeline_name = pipeline.get(
            "pipeline_name",
            "Unnamed Pipeline"
        )

        print(
            "\nPipeline: "
            f"{pipeline_name}"
        )

        print(
            "\n"
            + "-" * 50
        )

        steps = pipeline.get(
            "steps",
            []
        )

        if not steps:

            raise ValueError(
                "Pipeline contains no steps."
            )

        for index, step in enumerate(
            steps,
            start=1
        ):

            operation = (
                step.get(
                    "operation",
                    ""
                )
                .upper()
                .strip()
            )

            dataset = step.get(
                "dataset"
            )

            details = step.get(
                "details",
                ""
            )

            print(
                f"\nStep {index}: "
                f"{operation}"
            )

            # =================================================
            # LOAD
            # =================================================

            if operation == "LOAD":

                self.load_dataset(
                    dataset
                )

            # =================================================
            # CLEAN
            # =================================================

            elif operation == "CLEAN":

                self.clean_dataset(
                    dataset
                )

            # =================================================
            # TRANSFORM
            # =================================================

            elif operation == "TRANSFORM":

                self.transform_dataset(
                    dataset,
                    details
                )

            # =================================================
            # JOIN
            # =================================================

            elif operation == "JOIN":

                join_with = step.get(
                    "join_with"
                )

                join_key = step.get(
                    "join_key"
                )

                self.join_datasets(
                    dataset,
                    join_with,
                    join_key
                )

            # =================================================
            # STORE
            # =================================================

            elif operation == "STORE":

                self.store_result(
                    pipeline
                )

            # =================================================
            # VALIDATION
            # =================================================

            elif operation == "VALIDATION":

                self.validate_result()

            # =================================================
            # UNKNOWN OPERATION
            # =================================================

            else:

                print(
                    f"[WARNING] "
                    f"Unknown operation: "
                    f"{operation}"
                )

        # =====================================================
        # EXECUTION TIME
        # =====================================================

        execution_time = (
            time.perf_counter()
            - self.start_time
        )

        print(
            "\n"
            + "=" * 60
        )

        print(
            "LLM-GENERATED ETL PIPELINE COMPLETED"
        )

        print(
            "=" * 60
        )

        print(
            f"\nETL Execution Time: "
            f"{execution_time:.4f} seconds"
        )

        return self.final_result